CREATE TABLE [dbo].[ActivitiesList]
(
	[Id] INT NOT NULL PRIMARY KEY, 
	[Venue] NVARCHAR(50) NOT NULL, 
	[Address] NVARCHAR(50) NOT NULL, 
	[City] NVARCHAR(50) NOT NULL, 
	[State] NVARCHAR(50) NOT NULL, 
	[Zip] NVARCHAR(50) NOT NULL, 
	[Phone Number] NVARCHAR(50) NOT NULL, 
	[Price Per Person] NVARCHAR(50) NOT NULL, 
	[Link] NVARCHAR(MAX) NOT NULL, 
	[Days Open] NVARCHAR(50) NOT NULL, 
	[Times Open] NVARCHAR(50) NOT NULL
)
